[package]
name = "wattswap_hacknight"
version = "2.0.0"
authors = []

[addresses]
wattswap_addr = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
